### ISSUE TITLE
Share algorithm

### ISSUE THREAD

**Issue by aggsol** [tobiasvl/polarium-pwgen#1]
Do you mind sharing the algorithm for the Polarium passwords?

**Comment by tobiasvl** [comment]
@aggsol Haha, hey! How in the world did you find this old, empty repo? I have no idea why I never pushed this script. I've done so now! Not sure how useful it is though.

Here's the algorithm step by step (from [a devlog post](https://tobiasvl.itch.io/picolarium/devlog/41522/picolarium-10-level-editor-and-hints) I wrote for [a Polarium clone I made](https://github.com/tobiasvl/picolarium)):

1. Convert each row of the puzzle to a binary byte (8 bits): A black tile is 1, a white tile is 0.
   1. If a line is shorter than 8 tiles, pad it (with anything) at the end so it's 8 bits.)
   2. If there are fewer than 8 rows, add bytes (they can be anything) at the end so there are 8 in total.
2. Put together four and four bytes, so you have two 32-bit numbers that represent the board in binary.
3. Reverse the bits of each 32-bit number.
4. Now create a third 32-bit number with this metadata about the level:
   1. Size: The height of the level, in 4 bits
   2. Size: The width of the level, in 4 bits
   3. Hint: The Y coordinate of the starting position, in 4 bits (0 and 9 are the border tiles)
   4. Hint: The X coordinate of the starting position, in 4 bits
   5. Hint: The Y coordinate of the ending position, in 4 bits
   6. Hint: The X coordinate of the ending position, in 4 bits
   7. Checksum: Add all bytes you have so far together (that's 4+4+3 bytes, 11 in total). Put the last byte of the result in front of the other metadata bytes.
5. Now reverse the decimal digits of each 32-bit number. You have a password!

Or maybe [this blog post](https://jroatch.xyz/2011/blog/polarium-password-encoding) is easier to understand. It also explains the Polarium Advance passwords.

Hope this helps!

**Comment by aggsol** [comment]
Thank you!
